#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

JAVA8_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk
PATH="$JAVA8_HOME/bin:$PATH"
JAVA11_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk
PG96_HOME=/usr/local/opt/postgresql@9.6
NVM_DIR="$HOME/.nvm"
RBENV_DIR="$HOME/.rbenv"

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
