# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

HISTSIZE=1000000000
SAVEHIST=1000000000

setopt HIST_FIND_NO_DUPS
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY

setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT
setopt PUSHD_TO_HOME
setopt EXTENDED_GLOB
setopt CLOBBER

RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
# PATH="$RBENV_DIR/shims:$PATH"
eval "$(rbenv init -)"

alias pg_start="nohup pg_ctl -D /usr/local/var/postgres start &>/dev/null & disown"
alias pg96_start="nohup $PG96_HOME/bin/pg_ctl -D /usr/local/var/postgresql@9.6 start &>/dev/null & disown"
alias pg_stop="pg_ctl -D /usr/local/var/postgres stop"
alias pg96_stop="$PG96_HOME/bin/pg_ctl -D /usr/local/var/postgresql@9.6 stop"
alias pg_restart="nohup pg_ctl -D /usr/local/var/postgres restart &>/dev/null & disown"
alias pg96_restart="nohup $PG96_HOME/bin/pg_ctl -D /usr/local/var/postgresql@9.6 restart &>/dev/null & disown"
alias pg_status="pg_ctl -D /usr/local/var/postgres status"
alias pg96_status="$PG96_HOME/bin/pg_ctl -D /usr/local/var/postgresql@9.6 status"

# nvm can either be loaded deferred with alias or directly. alias method requires explicit path manipulation
# PATH="$NVM_DIR/versions/node/v$(<$NVM_DIR/alias/default)/bin:$PATH"
# alias nvm="unalias nvm; [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"; [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"; nvm $@"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

function export_env()
{
    builtin export "$@"
    if [[ ${#@} -eq 1 && "${@//[^=]/}" ]]
    then
        launchctl setenv "${@%%=*}" "${@##*=}"
    elif [[ ! "${@//[^ ]/}" ]]
    then
        launchctl setenv "${@}" "${=@}"
    fi
}

export_env JAVA_HOME=$JAVA8_HOME
export_env JDK_HOME=$JAVA8_HOME
export_env JRE_HOME=$JAVA8_HOME/jre
export_env ANDROID_HOME=/Users/kaan/dev/sdk/android-sdk-macosx/
export_env GIT_SSH_COMMAND=ssh
export_env PATH=$PATH
export_env LSCOLORS='ExGxBxDxCxEgEdxbxgxcxd'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
